# Generated by Django 3.2.13 on 2022-06-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_coursefeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
